### ISSUE TITLE
Add license key template to this chart

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh-enterprise-helm#6]
We should allow users to create a license key via this chart such that other components can read the license from a well-known (but still configurable) location.

**Comment by ashleywang1** [comment]
Some quick notes on the license key for the gloo-mesh-enterprise helm chart:

The values.yaml has the following lines:
```

license:
  key: ""
license_key: ""
licenseKey: ""
```

The license-secret.yaml template uses:
```
{{- $licenseKey := coalesce .Values.licenseKey .Values.license_key .Values.license.key }}
```
to decide which value it takes (in order, it's licenseKey, then license_key, then license.key)

The rbac-webhook deployment takes in the license key as an environment variable, which looks like:
```

    - name: LICENSE_KEY
      valueFrom:
        secretKeyRef:
          key: license-key
          name: gloo-mesh-license
```
